name: wiremi-iac

on:
  push:
    branches:
      - main

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  BUCKET_TF_STATE: ${{ secrets.BUCKET_TF_STATE }}
  AWS_REGION: us-east-1
  EKS_CLUSTER: wiremi-eks

jobs:
  build-terraform:
    name: Apply Terraform Code Changes
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
      
      - name: Setup Terraform with Specified Version
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.3
      
      - name: AWS Configure
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Init Terraform Project
        id: init
        run: terraform init -backend-config="bucket=${{ env.BUCKET_TF_STATE }}"
      
      - name: Format Terraform Files
        id: fmt
        run: terraform fmt -check

      - name: Validate Terraform
        id: validate
        run: terraform validate

      - name: Plan Terraform Execution
        id: plan
        run: terraform plan -no-color -input=false

      - name: Checking Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1

      - name: Apply Terraform
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve

      - name: Get Kube Config File
        id: getconfig
        if: steps.apply.outcome == 'success'
        run: aws eks update-kubeconfig --region ${{ env.AWS_REGION }} --name ${{ env.EKS_CLUSTER }}

      - name: Install Ingress Controller
        if: steps.apply.outcome == 'success' && steps.getconfig.outcome == 'success'
        run: kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.1.3/deploy/static/provider/aws/deploy.yaml
